### ISSUE TITLE
add sourceforge mode

### ISSUE THREAD

**Issue by kevinburke** [genuinetools/releases#3]
sometimes it's too easy to figure out the right way to download the binary, and I want it to be more challenging to figure out which link is the correct link. it would be good if there was a mode that would present 6 different "CLICK TO DOWNLOAD" ads for every one real link that downloads a real binary.

added bonus: with probability 0.001, clicking "download" on the real link should install malware (a bitcoin miner?) onto your machine!

**Comment by jessfraz** [comment]
lol clever :)
